swagger: '2.0'
info:
  description: 'This is barcamp 2021 api'
  openapi: '3.0.0'
  version: '1.0.0'
  title: 'Barcamp 2021'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'shaunmak@invanique.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'api.barcamp-2021.org'
basePath: '/v1'
schemes:
  - 'https'
  - 'http'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
